"""empty message

Revision ID: 28d2f8286594
Revises: b414acd761f1
Create Date: 2019-08-18 18:53:16.086031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d2f8286594'
down_revision = 'b414acd761f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_data', sa.Column('venue', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_game_data_venue'), 'game_data', ['venue'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_data_venue'), table_name='game_data')
    op.drop_column('game_data', 'venue')
    # ### end Alembic commands ###
