"""empty message

Revision ID: b414acd761f1
Revises: 5b5c2c9b53c0
Create Date: 2019-08-17 17:13:23.611685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b414acd761f1'
down_revision = '5b5c2c9b53c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_data', sa.Column('player_data_added', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_data', 'player_data_added')
    # ### end Alembic commands ###
