"""empty message

Revision ID: f77040475ccd
Revises: 625b7b7c5f11
Create Date: 2019-08-14 12:50:37.407174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77040475ccd'
down_revision = '625b7b7c5f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('game') as batch_op:
		batch_op.drop_column('game_result')
		batch_op.drop_column('date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('game_result', sa.VARCHAR(length=64), nullable=True))
    op.add_column('game', sa.Column('date', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
